CREATE TABLE GUILDS (
    ID int NOT NULL AUTO_INCREMENT,
    GUILD_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);



INSERT INTO swgohticketdb.GUILDS(
  GUILD_NAME
) VALUES (
  'Event HorizOn'  -- GUILD_NAME - IN text
);


CREATE TABLE LIFETIME_TICKETS (
    ID int NOT NULL AUTO_INCREMENT,
    GUILD_ID int,
    MEMBER_NAME VARCHAR(50),
    TICKETS BIGINT,
    M_DATE DATE,
    PRIMARY KEY (ID)
);