CREATE TABLE GUILDS (
    ID int NOT NULL AUTO_INCREMENT,
    GUILD_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);



INSERT INTO swgohticketdb.GUILDS(
  GUILD_NAME
) VALUES (
  'Event HorizOn'  -- GUILD_NAME - IN text
);


CREATE TABLE `LIFETIME_TICKETS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GUILD_ID` int(11) NOT NULL,
  `MEMBER_NAME` varchar(50) NOT NULL,
  `TICKETS` bigint(20) NOT NULL,
  `M_DATE` datetime DEFAULT NULL,
  `SOURCE_FILE` text CHARACTER SET utf16 COLLATE utf16_bin,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=154 DEFAULT CHARSET=latin1;

CREATE TABLE DATA_RUN (
    ID int NOT NULL AUTO_INCREMENT,
    RUN_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE `TICKETS_RUN` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `GUILD_ID` int(11) NOT NULL,
  `RUN_ID` int NOT NULL,
  `MEMBER_NAME` varchar(50) NOT NULL,
  `TICKETS` bigint(20) NOT NULL,
  `M_DATE` datetime DEFAULT NULL,
  `SOURCE_FILE` text CHARACTER SET utf16 COLLATE utf16_bin,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=154 DEFAULT CHARSET=latin1;

