select * from DATA_RUN;
select * from TICKETS_RUN 
  WHERE 1=1
  AND RUN_ID=12
  AND (TICKETS = 0 OR MEMBER_NAME = 'UNKNOWN')
  ;

select * from LIFETIME_TICKETS
  WHERE 1=1
  AND (TICKETS = 0 OR MEMBER_NAME = 'UNKNOWN')
  ;
  
select MEMBER_NAME, Count(*) from LIFETIME_TICKETS GROUP BY MEMBER_NAME;


UPDATE TICKETS_RUN SET MEMBER_NAME = 'Obi' WHERE ID = 494;
COMMIT;
UPDATE TICKETS_RUN SET TICKETS = 2400 WHERE ID = 453;
#25692 abraxis

select * from TICKETS_RUN where RUN_ID=12;

